### ISSUE TITLE
Errors pulling images from GHCR

### ISSUE THREAD

**Issue by joshgav** [cncf/podtato-head#66]
## Problem

I attempted to apply the `delivery/manifest` example, but got ImagePullErrors trying to pull `ghcr.io/podtato-head/podtato-main:v0.1.0` and the other containers from the kubelet. The specific error was "denied", which would indicate I need to add pull secrets:

```
Failed to pull image "ghcr.io/podtato-head/podtato-right-leg:v0.1.0": rpc error: code = Unknown desc = Error response from daemon: Head https://ghcr.io/v2/podtato-head/podtato-right-leg/manifests/v0.1.0: denied
```

So I followed [these instructions](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#authenticating-to-github-packages) and added a .dockerconfigjson secret for GHCR, added `imagePullSecrets` fields to the Deployments in the manifest and tried again. With this I got a new error, "name unknown", so authentication worked but the image wasn't found:

```
Failed to pull image "ghcr.io/podtato-head/podtato-right-leg:v0.1.0": rpc error: code = Unknown desc = Error response from daemon: name unknown
```

I couldn't find a way to solve this, it looks like the image isn't there, although it could be it's just private. Is there a way to browse public GHCR images to quickly verify an image/tag exists?

## Solutions

Could it be the image hasn't been marked for public use?

Could it be it hasn't been pushed?

Per what I've found, next steps could be:

- [ ] Document how to create a pull secret for GHCR (GitHub Container Registry), and add corresponding "imagePullSecrets" fields in PodSpecs around this repo.
- [ ] Push the images referenced in the manifest to the registry.

I'm happy to tackle item 1 but don't have access to handle item 2.

**Comment by AloisReitbauer** [comment]
OK, I found the issue. It seems that the images only get built on the main branch but not on this one.

**Comment by AloisReitbauer** [comment]
This should be fixed. The images were not built automatically

**Comment by joshgav** [comment]
Thank you, confirming it works now.

I did a quick search and don't see anything about rate limits for anonymous GHCR requests (a la Docker Hub) so no authn secret is necessary either.
