### ISSUE TITLE
Failing main build due to permission errors

### ISSUE THREAD

**Issue by AlexsJones** [cncf/podtato-head#94]
https://github.com/cncf/podtato-head/runs/3486233685?check_suite_focus=true

**Comment by joshgav** [comment]
Thanks @AlexsJones, I think there are two bugs here:

1. Revert to using `secrets.CR_PAT` for the container_build_main task, which pushes to `ghcr.io/podtato-head` and  perhaps requires a special secret. The `container_build_fork` task pushes to `ghcr.io/<repo_owner>/podtato-head`, for which `github.token` works.
2. Make the `ghcr.io/cncf/podtato-head` images/repos _public_ so kind can pull those images without a pull secret.

I'll submit a PR for 1, can you address 2? Thanks!

**Comment by AlexsJones** [comment]
@AloisReitbauer @thschue do you have permissions to make the podtato head container registry images public?

**Comment by AlexsJones** [comment]
Thank you @joshgav excellent stuff.

**Comment by joshgav** [comment]
Thanks @AlexsJones, at least #95 fixed the main container build, but I'm stumped for the moment on why the ensuing delivery tests for kubectl and helm still fail in this repo, would like to see logs and events. I have an idea to test further and will try later today, thanks for bearing with me!
